spring.application.name=springsecurityandjwt
spring.datasource.url=jdbc:postgresql://localhost:5432/monitoring_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.ddl-auto=none  아무것도 안 함 (기본값)
#spring.jpa.hibernate.ddl-auto=validate  Entity와 테이블 구조 비교, 없거나 다르면 에러
#spring.jpa.hibernate.ddl-auto=update 테이블 없으면 만들고, 컬럼 없으면 추가. 기존 데이터는 유지
#spring.jpa.hibernate.ddl-auto=create  애플리케이션 시작 시 기존 테이블 삭제 후 새로 생성
#spring.jpa.hibernate.ddl-auto=create-drop  create와 같지만, 앱 종료 시 테이블 삭제
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect 
#JWT 설정
jwt.secret=67OGocFzYPwt/QX5Yovh95OxyjIjdQBSH2PGdPsJFyyZrslIsV65Xt3z1q+ntBzAV90ulrG+qsDOcCMvVk0+bg==
jwt.access-expire=900000 
jwt.refresh-expire=604800000 
#Redis 설정
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=60000
management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoints.web.base-path=/actuator
management.endpoint.health.show-details=always