spring.application.name=springsecurityandjwt
spring.datasource.url=jdbc:postgresql://localhost:5432/monitoring_db
spring.datasource.username=postgres
spring.datasource.password=your_password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update  # create-drop에서 update로 변경
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect # WebSocket
# JWT 설정
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.AcessExpire=900000 # 15분
jwt.RefreshExpire=604800000 # 7일