spring.application.name=springsecurityandjwt
spring.datasource.url=jdbc:postgresql://localhost:5432/monitoring_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update  
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect 
# JWT 설정
jwt.secret=67OGocFzYPwt/QX5Yovh95OxyjIjdQBSH2PGdPsJFyyZrslIsV65Xt3z1q+ntBzAV90ulrG+qsDOcCMvVk0+bg==
jwt.access-expire=900000 
jwt.refresh-expire=604800000 
# Redis 설정
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=60000